.. Getting Started with Python
.. ---------------------------

Python 入門
-----------

.. New to Python? Let's properly setup up your Python environment.

Python を初めて使いますか？ Python 環境を適切にセットアップしましょう。

.. toctree::
   :maxdepth: 2

   starting/which-python

- Properly Install Python

 .. toctree::
    :maxdepth: 1

    starting/installation
    starting/install/osx
    starting/install/win
    starting/install/linux



.. Writing Great Python Code
.. -------------------------

大規模な Python コードを書く
--------------------------

.. This part of the guide focuses on the best-practices for writing Python code.

本書のこのパートは、Python コードを書くためのベストプラクティスに焦点を当てています。

.. toctree::
   :maxdepth: 2

   writing/structure
   writing/style
   writing/reading
   writing/documentation
   writing/tests
   writing/logging
   writing/gotchas
   writing/license



.. Scenario Guide for Python Applications
.. --------------------------------------

Python アプリケーションのシナリオガイド
---------------------------------------

.. This part of the guide focuses on tool and module advice based on
.. different scenarios.

本書のこのパートは、さまざまなシナリオに基づいたツールとモジュールのアドバイスに焦点を当てています。

.. toctree::
   :maxdepth: 2

   scenarios/client
   scenarios/web
   scenarios/scrape
   scenarios/cli
   scenarios/gui
   scenarios/db
   scenarios/network
   scenarios/admin
   scenarios/ci
   scenarios/speed
   scenarios/scientific
   scenarios/imaging
   scenarios/serialization
   scenarios/xml
   scenarios/json
   scenarios/crypto
   scenarios/ml
   scenarios/clibs


.. Shipping Great Python Code
.. --------------------------

大規模な Python コードへの出荷
----------------------------

.. This part of the guide focuses on deploying your Python code.

本書のこのパートは、Python コードのデプロイに焦点を当てています。

.. toctree::
   :maxdepth: 2

   shipping/packaging
   shipping/freezing


.. Python Development Environments
.. -------------------------------

Python 開発環境
---------------

.. This part of the guide focus on the Python development environment,
.. and the best-practice tools that are available for writing Python code.

本書のこのパートは、Python 開発環境と、Python コードの作成に使用できるベストプラクティスなツールに焦点を当てています。

.. toctree::
   :maxdepth: 2

   dev/env
   dev/virtualenvs
   dev/pip-virtualenv




.. Additional Notes
.. ----------------

その他の注意事項
----------------

.. This part of the guide, which is mostly prose, begins with some
.. background information about Python, then focuses on next steps.

本書のこのパートは、主に散文であり、Python に関する背景情報から始まり、次のステップに焦点を当てています。

.. toctree::
   :maxdepth: 2

   intro/duction
   intro/community
   intro/learning
   intro/documentation
   intro/news

.. .. note::
..    Notes defined within all diatonic and chromatic musical scales have been
..    intentionally excluded from this list of additional notes. Additionally,
..    this note.

.. note::
   全音階および半音の音階で定義された備考は、追加の備考のリストからは意図的に除外されています。この備考を付け加える。


--------------------------------------

.. Contribution notes and legal information (for those interested).

寄稿と法的情報（興味がある人向け）。

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide





