.. Getting Started with Python
.. ---------------------------

Python 入門
-----------

.. New to Python? Let's properly setup up your Python environment.

Python を初めて使う？適切に Python 環境をセットアップしましょう。

.. toctree::
   :maxdepth: 2

   starting/which-python

- Properly Install Python

 .. toctree::
    :maxdepth: 1

    starting/installation
    starting/install/osx
    starting/install/win
    starting/install/linux



.. Writing Great Python Code
.. -------------------------

偉大な Python コードを書く
--------------------------

.. This part of the guide focuses on the best-practices for writing Python code.

このガイドのこの部分では、Python コードを書くためのベストプラクティスに焦点を当てています。

.. toctree::
   :maxdepth: 2

   writing/structure
   writing/style
   writing/reading
   writing/documentation
   writing/tests
   writing/logging
   writing/gotchas
   writing/license



.. Scenario Guide for Python Applications
.. --------------------------------------

Python アプリケーションのシナリオガイド
---------------------------------------

.. This part of the guide focuses on tool and module advice based on
.. different scenarios.

このガイドのこの部分では、さまざまなシナリオに基づいたツールとモジュールのアドバイスに焦点を当てています。

.. toctree::
   :maxdepth: 2

   scenarios/client
   scenarios/web
   scenarios/scrape
   scenarios/cli
   scenarios/gui
   scenarios/db
   scenarios/network
   scenarios/admin
   scenarios/ci
   scenarios/speed
   scenarios/scientific
   scenarios/imaging
   scenarios/serialization
   scenarios/xml
   scenarios/json
   scenarios/crypto
   scenarios/ml
   scenarios/clibs


.. Shipping Great Python Code
.. --------------------------

偉大な Python コードへの輸送
----------------------------

.. This part of the guide focuses on deploying your Python code.

このガイドのこの部分では、Python コードのデプロイメントに焦点を当てています。

.. toctree::
   :maxdepth: 2

   shipping/packaging
   shipping/freezing


.. Python Development Environments
.. -------------------------------

Python 開発環境
---------------

.. This part of the guide focus on the Python development environment,
.. and the best-practice tools that are available for writing Python code.

本書のこの部分では、Python 開発環境と、Python コードの作成に使用できるベストプラクティスツールに焦点を当てています。

.. toctree::
   :maxdepth: 2

   dev/env
   dev/virtualenvs
   dev/pip-virtualenv




.. Additional Notes
.. ----------------

その他の注意事項
----------------

.. This part of the guide, which is mostly prose, begins with some
.. background information about Python, then focuses on next steps.

主に散文であるこのガイドの部分は、Python に関する背景情報から始まり、次のステップに焦点を当てています。

.. toctree::
   :maxdepth: 2

   intro/duction
   intro/community
   intro/learning
   intro/documentation
   intro/news

.. .. note::
..    Notes defined within all diatonic and chromatic musical scales have been
..    intentionally excluded from this list of additional notes. Additionally,
..    this note.

.. note::
   すべての音階および音階の音階で定義された音符は、この追加音符のリストから意図的に除外されています。 さらに、このメモ。


--------------------------------------

.. Contribution notes and legal information (for those interested).

寄付メモと法的情報（興味がある人向け）。

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide





